version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=memes
    restart: unless-stopped

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data: